### ISSUE TITLE
Login failed in v1

### ISSUE THREAD

**Issue by Dimitrius1** [glad-tidings/BoinkersBot#1]
Login failed in v1
Log:
[Boinkers] [...] login failed
[Boinkers] [...] sync sleep '2h 1m 27s'

Creation new session not working also.

**Comment by glad-tidings** [comment]
use vpn

**Comment by Dimitrius1** [comment]
> use vpn

Creation new session is work. my bad.
But with using vpn
[...] login failed
[...] sync sleep '2h 44m 8s'

**Comment by glad-tidings** [comment]
don't use proxy or change your vpn

**Comment by glad-tidings** [comment]
![Screenshot 2024-12-14 070806](https://github.com/user-attachments/assets/a71d4603-e0e7-49ac-b71d-14fa4a5142cd)

**Comment by Dimitrius1** [comment]
Very interesting, but I've already tried with and without VPN, run on other PCs and still the error:

[Boinkers] [...] login failed

Bums and Seed bots work fine.

**Comment by glad-tidings** [comment]
boinkers protected by cloudflare and public vpn usually don't work

**Comment by glad-tidings** [comment]
![Screenshot 2024-12-17 112628](https://github.com/user-attachments/assets/86d2d762-f451-4a15-b115-fc218255a837)
If you can obtain the Boinker token manually, create a folder named 'cache' and then create a file called 'Boinkers-accountname.cache' to write the token into. Make sure to replace 'accountname' with the account name found in the date.txt file.

**Comment by Dimitrius1** [comment]
Tried it, have same issue. 
Apparently they do have some kind of defense.
Okay, maybe I'll look for something else.
Thanks.
